version: "3.8"

services:
  app:
    build:
      context: ../app          # <- desde infra/ sube a app/
      dockerfile: Dockerfile
    container_name: prueba2
    ports:
      - "3001:3000"            # host:container
    restart: unless-stopped

